### ISSUE TITLE
Sending Door Open Signal 

### ISSUE THREAD

**Issue by shrynx** [plusvic/simplebus2-intercom#1]
Thanks for putting your work in open and described in detail !

I was wondering have you tried to make it work the other way round, sending door open signal from your desk o the intercom ?
Any tips/directions how to achieve that ?

**Comment by plusvic** [comment]
Yes, messages can be sent in both directions. I updated the repository with more recent changes in `remote_unit/src/main.cpp`. The `transmitMessage` function can send any message to the intercom.

**Comment by shrynx** [comment]
Sweet ! and thanks again
