### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by thomasvt1** [plusvic/simplebus2-intercom#2]
Hey, this looks awesome! I was just wondering, did you make the PCB yourself or did you create/build/assemble is somewhere?

simplebus2-repeater.kicad_pcb seems to be empty so jlcpcb.com seems to be a no-go

**Comment by plusvic** [comment]
I built the PCB using a soldering breadboard, didn't printed a proper PCB.

**Comment by FilippoPiazza** [comment]
Can you show the pcb? It's not seen in the pictures

**Comment by Elektroarzt** [comment]
If someone is interested, I made an Eval-Board for easy measurement of power and some key signals with an additional connection possibility to a D1 mini. If needed I could upload the Gerber data. If someone has a software solution for a D1 mini or ESP32, I would be grateful to participate and could adapt to the PCB design.

![Simplebus2 Eval-Board 1](https://user-images.githubusercontent.com/61664171/216811299-6bfec678-056a-4197-aebd-9f5a4e599c54.jpeg)

![Simplebus2 Eval-Board 2](https://user-images.githubusercontent.com/61664171/216811301-5af3dc5f-438a-448d-8dcc-195da13e3ddb.jpeg)

**Comment by VideoScape** [comment]
> If someone is interested, I made an Eval-Board for easy measurement of power and some key signals with an additional connection possibility to a D1 mini. If needed I could upload the Gerber data. If someone has a software solution for a D1 mini or ESP32, I would be grateful to participate and could adapt to the PCB design.
> 
> ![Simplebus2 Eval-Board 1](https://user-images.githubusercontent.com/61664171/216811299-6bfec678-056a-4197-aebd-9f5a4e599c54.jpeg)
> 
> ![Simplebus2 Eval-Board 2](https://user-images.githubusercontent.com/61664171/216811301-5af3dc5f-438a-448d-8dcc-195da13e3ddb.jpeg)

I would happy buy your PCB, in the UK I can buy PIC12F508, I haven't done anything like this before so it is pretty new for me but I want to give this ago as this door intercom is the last bit that is not smart in my place.

**Comment by Elektroarzt** [comment]
Hi [VideoScape](https://github.com/VideoScape),
please be aware, that this PCB is work in progress and is no plug-and-play solution. If you like to participate in developing, this could be a good starting point. I could send you a unit with schematics for self-cost, please give me an e-mail to handle this. In return I would like to participate in your findings and an ESP-based firmware if you plan to do so.
As plusvic already stated, the linear power supply is not sufficient for the ESP. Not the S2 bus voltage is dropping, but the thermal protection of the linear power regulator. Would be better to use a step-down-converter. The PCB gives you all possibilities for that.

**Comment by richardneitzke** [comment]
Hi @Elektroarzt!

Looks like you've already made some progress on the hardware-side, I'm currently looking into building an ESP8266/ESP32-based bridge as well but I just got started (had a look at the signals with my scope today).

My initial plan for drawing power from the bus was to use one of these cheap LM2596 boards I have lying around but connecting one killed the bus (even without drawing any current, maybe it's the capacitor across the input). What do you use for power on your board?

**Comment by Elektroarzt** [comment]
Using the linear regulator with the ESP results in brownouts, so I also used a LM2596 but had no issues with the bus at first sight. Did you connect behind the low pass filter like in plusvic's schematic?
I think Gurkenflieger is miles ahead with his ESP development approach: https://github.com/plusvic/simplebus2-intercom/issues/5. Maybe this will be the better path.

**Comment by Gurkenflieger** [comment]
Hey i now see your devboard. It looks pretty nice. Maybe we can work together and get a working solution. My Esp32 powers fine using a Geptach 3.3 1A Voltage regulator. The problem is, that the outdoor ring is damped if there is a load. I also used a Seeduino Xiao with the same results. But i found a solution. Im not listening to the code  from the outdoor ringing signal, im looking for the 3 short bursts which seems like an ack from the intercom. Generally signals from the intercom can be decoded because of the higher amplitude.
Some pictures from the dampened and non dampened signal. In the next days i will test my new code.
![Uploading CD3A91E2-9E03-4799-A29F-155E071484FB.jpeg…]()

**Comment by Gurkenflieger** [comment]
![C2F09AA8-B2C5-4FF3-A86D-674EF8118407](https://github.com/plusvic/simplebus2-intercom/assets/92711986/03954eb9-de84-4250-9cdd-3a1de8a471fa)

**Comment by Gurkenflieger** [comment]
![Uploading AC360B84-6A4E-4699-9CF6-66F649A49109.jpeg…]()

**Comment by Gurkenflieger** [comment]
![5C9F019E-07AC-418F-A0C1-F86DF9946ACB](https://github.com/plusvic/simplebus2-intercom/assets/92711986/8c5ed4ad-50fa-4c4e-b486-68a3f92022bf)

**Comment by issalig** [comment]
@Elektroarzt would you mind to share your pcb/software? My idea is to connect an ESP32 or even a RPIZero to manage the video/audio and not start from zero if possible.

**Comment by Elektroarzt** [comment]
I had some really productive and funny hours of teamwork with [Gurkenflieger](https://github.com/Gurkenflieger) on this project. Outcome was a V2.0 of the PCB and a newly coded software for Comelit systems based on [plusvics](https://github.com/plusvic) work. We had the plan of publishing to a GitHub, but had not the time until today. I talked to [Gurkenflieger](https://github.com/Gurkenflieger) concerning the video option. From what we see, this function could be solved in best case with a Piggy-Back on the V2.0 PCBA (see pin headers J2 and J3 in the following pictures). It is populated with a Seeedstudio XIAO ESP32C3 wich should be potential enough for this task. Please be patient until we have the time to publish.

![Mittel (Simplebus MQTT Bridge V2 0 Pic4)](https://github.com/plusvic/simplebus2-intercom/assets/61664171/3bd765ca-6ebf-4322-bf2a-cff87bbcb585)
![Mittel (Simplebus MQTT Bridge V2 0 Pic5)](https://github.com/plusvic/simplebus2-intercom/assets/61664171/86c3be73-529c-4ac1-ac80-a8bd9ae055a9)
![Mittel (Simplebus MQTT Bridge V2 0 Pic2)](https://github.com/plusvic/simplebus2-intercom/assets/61664171/15ea2756-d622-4c0f-a23b-1a509d0defcf)
![Mittel (Simplebus MQTT Bridge V2 0 Pic3)](https://github.com/plusvic/simplebus2-intercom/assets/61664171/59028f65-c8ad-4aa8-b1d2-61a8ed68e56d)
![Mittel (Simplebus MQTT Bridge V2 0 Pic1)](https://github.com/plusvic/simplebus2-intercom/assets/61664171/805a1d74-fb70-4405-b2b5-fb315aa98c77)

**Comment by issalig** [comment]
It looks great.
The problem to read the video is not the power of a ESP32 (that I think is capable) but to implement CVBS capture, that's why I was thinking on using a rpi zero and usb capturer.
Anyway, I will stay tuned.

**Comment by quentinjourdan** [comment]
> I had some really productive and funny hours of teamwork with [Gurkenflieger](https://github.com/Gurkenflieger) on this project. Outcome was a V2.0 of the PCB and a newly coded software for Comelit systems based on [plusvics](https://github.com/plusvic) work. We had the plan of publishing to a GitHub, but had not the time until today. I talked to [Gurkenflieger](https://github.com/Gurkenflieger) concerning the video option. From what we see, this function could be solved in best case with a Piggy-Back on the V2.0 PCBA (see pin headers J2 and J3 in the following pictures). It is populated with a Seeedstudio XIAO ESP32C3 wich should be potential enough for this task. Please be patient until we have the time to publish.
> 
> ![Mittel (Simplebus MQTT Bridge V2 0 Pic4)](https://private-user-images.githubusercontent.com/61664171/272495760-3bd765ca-6ebf-4322-bf2a-cff87bbcb585.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjI1OTMsIm5iZiI6MTcwNDgyMjI5MywicGF0aCI6Ii82MTY2NDE3MS8yNzI0OTU3NjAtM2JkNzY1Y2EtNmViZi00MzIyLWJmMmEtY2ZmODdiYmNiNTg1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjI5ZjIzMjhiMzhkYTllMmQyZjI1NmI1ODViOTlhMGQ2NTRkNzdhMjZlZGMwZTQ1NGUwZjdkNzQ0YTZiNmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9g_6lLgnbEtrkN1cnY3hkNdEYM3hOuVPl2s9CkOgk7A) ![Mittel (Simplebus MQTT Bridge V2 0 Pic5)](https://private-user-images.githubusercontent.com/61664171/272495755-86c3be73-529c-4ac1-ac80-a8bd9ae055a9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjI1OTMsIm5iZiI6MTcwNDgyMjI5MywicGF0aCI6Ii82MTY2NDE3MS8yNzI0OTU3NTUtODZjM2JlNzMtNTI5Yy00YWMxLWFjODAtYThiZDlhZTA1NWE5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzFkYzNiMWQxNDVkMDJlZTRmZGUzNTkxYzEzNjY3YWQ0MWM1MmFmZWNjYWVjNWNjMDFmMmRhZTRkNzAwMWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y4XciTnp6C9bxQ8IXjrd8HlVijcjUJjOudsOucfR2w4) ![Mittel (Simplebus MQTT Bridge V2 0 Pic2)](https://private-user-images.githubusercontent.com/61664171/272495763-15ea2756-d622-4c0f-a23b-1a509d0defcf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjI1OTMsIm5iZiI6MTcwNDgyMjI5MywicGF0aCI6Ii82MTY2NDE3MS8yNzI0OTU3NjMtMTVlYTI3NTYtZDYyMi00YzBmLWEyM2ItMWE1MDlkMGRlZmNmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OWQzYzY0M2JjMmM2ZTdmMDFmMzRhMDFkZDFmZjgxNmQ4NzlkOTY3MTkzNTA1YWRlZmY3ODBhZDM0OTBhMjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AM8ZkD94AxwE9g4eLgHiW41tsVZgRd7roUwb4ULFuUI) ![Mittel (Simplebus MQTT Bridge V2 0 Pic3)](https://private-user-images.githubusercontent.com/61664171/272495762-59028f65-c8ad-4aa8-b1d2-61a8ed68e56d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjI1OTMsIm5iZiI6MTcwNDgyMjI5MywicGF0aCI6Ii82MTY2NDE3MS8yNzI0OTU3NjItNTkwMjhmNjUtYzhhZC00YWE4LWIxZDItNjFhOGVkNjhlNTZkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODMwNDNjODJlNmNiY2JmMDM1Y2E3NjkzY2YxZDdiYzI3MGU4ZDVhZThjMDJiMzc1YzQyMTczZmY5YmNkNGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z67rzeuoqk0I9fITXzFfBCEm7swV5GXIQWnODbCSNoE) ![Mittel (Simplebus MQTT Bridge V2 0 Pic1)](https://private-user-images.githubusercontent.com/61664171/272495767-805a1d74-fb70-4405-b2b5-fb315aa98c77.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjI1OTMsIm5iZiI6MTcwNDgyMjI5MywicGF0aCI6Ii82MTY2NDE3MS8yNzI0OTU3NjctODA1YTFkNzQtZmI3MC00NDA1LWIyYjUtZmIzMTVhYTk4Yzc3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxNzQ0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2UzYTE5NWE1OThkNzQ2NGVlZmI2YjM4OTM1MGExODMxNWNjNDgxYzM5ZWRiMTA3NDIwMDY0MDNjM2M0M2M0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jr9Ej0P8uLze3cDF4bz7n_gW9y634e-I-LOslT_qJEY)

Incredible @Elektroarzt  @Gurkenflieger, do you plan to release the code/pcb files or kit ? I’m very interested for my appartement

**Comment by Gurkenflieger** [comment]
I forgot about it but i can post the code in the next days. In my Apartment its working finde since months, but i think that @Elektroarzt has some trouble.

**Comment by Elektroarzt** [comment]
> Incredible @Elektroarzt @Gurkenflieger, do you plan to release the code/pcb files or kit ? I’m very interested for my appartement

I'm uploading hardware and mechanics right now to an own GitHub page. What do you need for the start? It's a bit more stuff. In V2.0 of the PCB there was a pinout bug that had to be routed by hand. I made a V2.1 PCB, that I have to test the next days. Therefor I will make a small batch of V2.1 if you are interested in a kit.
Software was coded by @Gurkenflieger, who will upload shortly.

**Comment by se-bastiaan** [comment]
> Therefor I will make a small batch of V2.1 if you are interested in a kit.

If you end up doing this, definitely let me know :)

**Comment by VideoScape** [comment]
> > Incredible @Elektroarzt @Gurkenflieger, do you plan to release the code/pcb files or kit ? I’m very interested for my appartement
> 
> I'm uploading hardware and mechanics right now to an own GitHub page. What do you need for the start? It's a bit more stuff. In V2.0 of the PCB there was a pinout bug that had to be routed by hand. I made a V2.1 PCB, that I have to test the next days. Therefor I will make a small batch of V2.1 if you are interested in a kit. Software was coded by @Gurkenflieger, who will upload shortly.

Very interested as well,  I would buy some as well.

**Comment by richardneitzke** [comment]
Same here, I’d love to buy a kit!

**Comment by Elektroarzt** [comment]
I don't want to spam this issue. So if you are interested in the above spinoff project, go to [this](https://github.com/Elektroarzt/simplebus2-mqtt-bridge/tree/main) project page. I will open up an issue there for the PCBA to keep you in the loop.
A lot of thanks for the great work so far go to @plusvic!
