### ISSUE TITLE
Capacitors types and values

### ISSUE THREAD

**Issue by prtngrm** [plusvic/simplebus2-intercom#9]
Hi,
I would like to make this project but I'm not an electronic expert.
Could someone tell what is the type and voltage values of each capacitor?

Also which type of diodes for the full bridge rectifier?

**Comment by plusvic** [comment]
C1 and C2 are electrolytic capacitors, C3 is a ceramic capacitor.

Values are in the [schematic](https://user-images.githubusercontent.com/182937/119274823-27513a00-bc12-11eb-81a5-44e7b55a2baf.png)

C1 = 150 microF anything above 50V
C2 = 220 microF anything above 10V
C3 = 100 nanoF any common ceramic capacitor should work

For the diodes the 1N4001 or 1N4002 should work fine.

**Comment by prtngrm** [comment]
Thanks !
